# -*- coding: utf-8 -*-
"""game_functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1exPbxP1U3pc4QtA0xrLfF2GzqIP1dAkL
"""

import random

def fun_game(die_sides):
  """This is a game to roll a users sided die 5 times"""
  die_rolls=[random.randint(1, die_sides) for die in range(5)]
  return die_rolls

def number_game():
  secret=random.randint(1,10)
  guess=int(input("guess a number between 1 and 10"))
  if guess == secret:
    return "you won"
  else:
    return "you lost"

fun_game(20)
number_game()